site_name: NH Switch Guide
copyright: Copyright &copy; 2024 <a href="https://discord.gg/C29hYvh" target="_blank">Nintendo Homebrew</a>, Maintained by the <a href="/switch-guide/about">NH Discord Server</a>.
site_description: Switch CFW Guide.
site_author: NH Discord Server.
site_url: https://guide.suchmeme.nl/
repo_url: https://github.com/nh-server/switch-guide
repo_name: NH Switch Guide

theme:
  name: material
  favicon: img/favicon.ico
  features:
    - toc.integrate
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - navigation.tracking

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/wrench

nav:
    - Home: index.md
    - User Guide:
        - 'Getting Started': 'user_guide/getting_started.md'
        - RCM:
          - 'Introduction': 'user_guide/rcm/index.md'
          - 'Entering RCM': 'user_guide/rcm/entering_rcm.md'
          - 'Sending a payload': 'user_guide/rcm/sending_payload.md'
        - Modchip:
          - 'Introduction': 'user_guide/modchip/index.md'
          - 'Preparing Hekate': 'user_guide/modchip/preparing_hekate.md'
        - Finalizing Setup:
          - 'Choosing an Environment': 'user_guide/all/cfw_environment.md'
          - 'Partitioning the SD for emuMMC': 'user_guide/all/partitioning_sd.md'
          - 'Partitioning the SD for sysCFW': 'user_guide/all/partitioning_sd_syscfw.md'
          - 'SD preparations': 'user_guide/all/sd_preparation.md'
          - 'Making Essential Backups': 'user_guide/all/making_essential_backups.md'
          - 'Launching CFW': 'user_guide/all/launching_cfw.md'
    - Homebrew:
      - 'Homebrew': 'homebrew/index.md'
      - 'JKSV': 'homebrew/jksv.md'
      - 'Goldleaf': 'homebrew/goldleaf.md'
      - 'FTPD': 'homebrew/ftpd.md'
      - 'NXTheme Installer': 'homebrew/nxtheme-installer.md'
      - 'NX-Shell': 'homebrew/nx-shell.md'
      - 'EdiZon': 'homebrew/edizon.md'
      - 'Tesla-Menu': 'homebrew/tesla-menu.md'
      - 'MissionControl': 'homebrew/mission-control.md'
      - 'sys-con': 'homebrew/sys-con.md'
      - 'sys-botbase': 'homebrew/sys-botbase.md'
      - 'SysDVR': 'homebrew/sysdvr.md'
      - 'sys-clk': 'homebrew/sys-clk.md'
      - 'ldn_mitm': 'homebrew/ldn_mitm.md'
    - Tutorials:
        - 'Extras': 'extras/index.md'
        - 'Blocking Nintendo servers': 'extras/blocking_nintendo.md'
        - 'Restoring a NAND Backup': 'extras/nandrestore.md'
        - 'AutoRCM': 'extras/autorcm.md'
        - 'Game Modding': 'extras/game_modding.md'
        - 'Linux injection without root': 'extras/adding_udev.md'
        - 'Showing File Name Extensions (Windows)': 'extras/showing_file_extensions.md'
        - 'Alternate Boot Setups': 'extras/alternate_bootsetups.md'
        - 'RCM Payload Injectors Information': 'extras/rcm_injectors.md'
        - 'Updating CFW': 'extras/updating.md'
        - 'Changing SD cards': 'extras/transfer_sd.md'
        - 'Glossary': 'extras/glossary.md'
        - 'Installing Android': 'extras/installing_android.md'
        - 'Installing Linux': 'extras/installing_linux.md'
    - FAQ: faq.md
    - About: about.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      toc_depth: 3

extra_css:
    - css/custom.css
